version: "3.9"

services:
  postgres:
    container_name: next_postgres
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
  # next:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: next
  #   restart: always
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - 3000:3000
  mailcatcher:
    container_name: mailcatcher
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    expose:
      - 1080
      - 1025
    ports:
      - "8080:1080"
      - "8025:1025"
