import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useSession, signIn, signOut } from "next-auth/react"

import styles from '../styles/Login.module.css'

const Login: NextPage = () => {
  const { data: session } = useSession()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Login
        </h1>
        <button onClick={() => signIn()}>Sign in</button>
      </main>
    </div>
  )
}

export default Login
