name: gather-participants
on:
  schedule:
    - cron: '0 18 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://room.fete.gg/api/update_participants' \
          --header 'authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
